
const STORAGE='loma-chaos-surveys-v1';
const seed=[{id:'S-100',title:'Clima de equipo',description:'Encuesta interna de ejemplo',created:'02/10/2026',questions:[{text:'¿Cómo evaluás la experiencia?',type:'Choice',options:['Muy buena','Buena','Regular']},{text:'¿La recomendarías?',type:'Sí/No',options:[]},{text:'Comentarios',type:'Texto Libre',options:[]}]}];
let surveys=JSON.parse(localStorage.getItem(STORAGE)||'null')||seed;let selectedId=null;let editingId=null;let chaosOn=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(STORAGE,JSON.stringify(surveys));}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo(0,0)}
function renderList(filter=''){const box=$('#surveyList');const f=filter.toLowerCase();const rows=surveys.filter(s=>s.title.toLowerCase().includes(f));box.innerHTML=rows.map(s=>`<div class="survey-row ${s.id===selectedId?'selected':''}" data-id="${s.id}" data-testid="survey-${s.id}"><strong>${escapeHtml(s.title)}</strong><small>${s.created} · ${s.questions.length} pregunta(s)</small></div>`).join('')||'<p class="hint">Sin resultados</p>'; $$('.survey-row').forEach(r=>r.onclick=()=>selectSurvey(r.dataset.id));}
function selectSurvey(id){selectedId=id;const s=surveys.find(x=>x.id===id);renderList($('#searchSurvey').value);$('#editSurvey').disabled=false;$('#deleteSurvey').disabled=false;$('#detailEmpty').classList.add('hidden');$('#surveyDetail').classList.remove('hidden');$('#surveyDetail').innerHTML=`<div class="detail-card"><p class="hint">${s.id}</p><h2>${escapeHtml(s.title)}</h2><p>${escapeHtml(s.description)}</p><p><b>Preguntas:</b> ${s.questions.length}</p><button class="btn secondary" id="previewSelected">Vista móvil</button></div>`;$('#previewSelected').onclick=()=>openMobile(s.id)}
function escapeHtml(v=''){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function renderQuestions(values=[]){let n=Math.max(1,Math.min(5,Number($('#questionCount').value)||1));$('#questionCount').value=n;const box=$('#questions');box.innerHTML='';for(let i=0;i<n;i++){const q=values[i]||{text:'',type:i===0?'Choice':i===1?'Sí/No':'Texto Libre',options:[]};box.insertAdjacentHTML('beforeend',`<section class="question" data-q="${i}"><div class="question-head"><b>Pregunta ${i+1}</b><span class="hint">Obligatoria</span></div><div class="field"><input class="q-text" data-testid="question-${i+1}" value="${escapeHtml(q.text)}" placeholder="Escriba la pregunta"></div><div class="field"><label>Tipo de Pregunta ${i+1}</label><select class="q-type" data-testid="type-${i+1}"><option ${q.type==='Choice'?'selected':''}>Choice</option><option ${q.type==='Sí/No'?'selected':''}>Sí/No</option><option ${q.type==='Texto Libre'?'selected':''}>Texto Libre</option></select></div><div class="field options-wrap ${q.type==='Choice'?'':'hidden'}"><label>RespuestaOpción1. Concatenar entre ";"</label><input class="q-options" data-testid="options-${i+1}" value="${escapeHtml((q.options||[]).join(';'))}" placeholder="opcion1;opcion2;opcion3"><span class="hint">Use punto y coma para separar opciones.</span></div></section>`)}$$('.q-type').forEach(x=>x.onchange=()=>x.closest('.question').querySelector('.options-wrap').classList.toggle('hidden',x.value!=='Choice'))}
function resetForm(){editingId=null;$('#formTitle').textContent='Creación de Encuesta';$('#surveyTitle').value='';$('#surveyDescription').value='';$('#questionCount').value=1;$('#formMessage').className='message hidden';renderQuestions();$('#downloadQr').disabled=true}
function validateForm(){const errs=[];if(!$('#surveyTitle').value.trim())errs.push('Ingrese el título de la encuesta.');if(!$('#surveyDescription').value.trim())errs.push('Ingrese la descripción.');$$('.question').forEach((q,i)=>{if(!q.querySelector('.q-text').value.trim())errs.push(`Complete la pregunta ${i+1}.`);if(q.querySelector('.q-type').value==='Choice'){const v=q.querySelector('.q-options').value.trim();if(!v)errs.push(`Ingrese opciones para la pregunta ${i+1}.`);if(v.includes(',')&&!v.includes(';'))errs.push(`En la pregunta ${i+1}, separe las opciones con punto y coma.`)}});return errs}
function collect(){return {id:editingId||'S-'+Date.now(),title:$('#surveyTitle').value.trim(),description:$('#surveyDescription').value.trim(),created:new Date().toLocaleDateString('es-AR'),questions:$$('.question').map(q=>({text:q.querySelector('.q-text').value.trim(),type:q.querySelector('.q-type').value,options:q.querySelector('.q-options').value.split(';').map(x=>x.trim()).filter(Boolean)}))}}
function submitSurvey(){const errors=validateForm();if(errors.length){$('#formMessage').className='message danger';$('#formMessage').innerHTML=errors.join('<br>');return}const data=collect();if(chaosOn&&$('#chaosDuplicate').checked){surveys.push(data,{...data,id:data.id+'-DUP'});}else if(editingId){surveys=surveys.map(s=>s.id===editingId?data:s)}else surveys.push(data);save();$('#formMessage').className='message ok';$('#formMessage').textContent='Encuesta creada con éxito. Descargue QR.';$('#downloadQr').disabled=false;toast(editingId?'Encuesta actualizada':'Encuesta creada');}
function editSelected(){const s=surveys.find(x=>x.id===selectedId);if(!s)return;editingId=s.id;show('createScreen');$('#formTitle').textContent='Editar Encuesta';$('#surveyTitle').value=s.title;$('#surveyDescription').value=s.description;$('#questionCount').value=s.questions.length;renderQuestions(s.questions)}
function deleteSelected(){if(!selectedId)return;if(confirm('¿Borrar la encuesta seleccionada?')){surveys=surveys.filter(s=>s.id!==selectedId);selectedId=null;save();renderList();$('#surveyDetail').classList.add('hidden');$('#detailEmpty').classList.remove('hidden');$('#editSurvey').disabled=$('#deleteSurvey').disabled=true;toast('Encuesta eliminada')}}
function openMobile(id){const s=surveys.find(x=>x.id===id)||surveys[surveys.length-1];if(!s){toast('Primero cree una encuesta');return}show('mobileScreen');$('#mobileTitle').textContent=s.title;$('#mobileDescription').textContent=s.description;$('#mobileQuestions').innerHTML=s.questions.map((q,i)=>`<div class="answer-block"><b>${i+1}. ${escapeHtml(q.text)}</b>${q.type==='Choice'?`<select data-testid="answer-${i+1}"><option value="">Seleccione</option>${q.options.map(o=>`<option>${escapeHtml(o)}</option>`).join('')}</select>`:q.type==='Sí/No'?`<label><input type="radio" name="a${i}" value="Sí"> Sí</label> <label><input type="radio" name="a${i}" value="No"> No</label>`:`<textarea data-testid="answer-${i+1}" placeholder="Respuesta"></textarea>`}</div>`).join('')}
function runChaos(type){const log=$('#chaosLog');const add=t=>log.textContent+=`\n${new Date().toLocaleTimeString()} ${t}`;if(type==='fill'){show('createScreen');resetForm();$('#surveyTitle').value='🔥 QA <script>alert(1)</'+'script> '+ 'A'.repeat(180);$('#surveyDescription').value="' OR 1=1 -- & caracteres <> 💥";$('#questionCount').value=5;renderQuestions();$$('.q-text').forEach((x,i)=>x.value=`Pregunta caos ${i+1} ${'X'.repeat(80)}`);$$('.q-options').forEach(x=>x.value='opción 1,con coma;opción 2;🚀');add('Datos extremos cargados.');}if(type==='offline'){document.body.classList.toggle('offline');add('Red simulada: '+(document.body.classList.contains('offline')?'OFFLINE':'ONLINE'));toast(document.body.classList.contains('offline')?'Sin conexión simulada':'Conexión restaurada')}if(type==='session'){show('homeScreen');add('Sesión expirada: navegación reiniciada.');toast('La sesión expiró. Ingrese nuevamente.')}if(type==='bulk'){for(let i=0;i<50;i++)surveys.push({id:'CHAOS-'+Date.now()+'-'+i,title:`Encuesta masiva ${i+1}`,description:'Dato generado para carga',created:new Date().toLocaleDateString('es-AR'),questions:[{text:'Pregunta de carga',type:'Texto Libre',options:[]}]});save();renderList();add('50 encuestas generadas.');}if(type==='clear'){surveys=[...seed];save();renderList();add('Datos restablecidos.')}}
function init(){renderList();renderQuestions();$('#homeAdmin').onclick=()=>show('menuScreen');$('#homeScan').onclick=()=>openMobile();$('#menuSurveys').onclick=()=>{show('adminScreen');renderList()};$('#menuLunch').onclick=()=>toast('Módulo Almuerzos simulado');$('#createSurvey').onclick=()=>{resetForm();show('createScreen')};$('#editSurvey').onclick=editSelected;$('#deleteSurvey').onclick=deleteSelected;$('#searchSurvey').oninput=e=>renderList(e.target.value);$('#questionCount').onchange=()=>renderQuestions();$('#resetForm').onclick=resetForm;$('#submitSurvey').onclick=submitSurvey;$('#downloadQr').onclick=()=>toast('QR descargado (simulación)');$('#mobileSubmit').onclick=()=>{$('#mobileMessage').className='message ok';$('#mobileMessage').textContent=`Has respondido correctamente a la encuesta ${$('#mobileTitle').textContent}.`};$$('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));$('#chaosToggle').onclick=()=>{$('#chaosPanel').classList.toggle('hidden');chaosOn=!$('#chaosPanel').classList.contains('hidden')};$$('[data-chaos]').forEach(b=>b.onclick=()=>runChaos(b.dataset.chaos));}
document.addEventListener('DOMContentLoaded',init);
